// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxmiAg550tVkBW4_zPijLVIG_kA_YH44E',
    appId: '1:507247752159:web:da06cb67117d4206100a6a',
    messagingSenderId: '507247752159',
    projectId: 'flutter-basics-85cec',
    authDomain: 'flutter-basics-85cec.firebaseapp.com',
    storageBucket: 'flutter-basics-85cec.appspot.com',
    measurementId: 'G-XJL9HZ5MJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6pqbcRhw6m-GAyQ83y5vDFLIzLfs6K6s',
    appId: '1:507247752159:android:3d7edc77f25bef6a100a6a',
    messagingSenderId: '507247752159',
    projectId: 'flutter-basics-85cec',
    storageBucket: 'flutter-basics-85cec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9nF-HMtjQT7l3M2k0Hhfk-8emfNnYFzo',
    appId: '1:507247752159:ios:02a972d19bb7301e100a6a',
    messagingSenderId: '507247752159',
    projectId: 'flutter-basics-85cec',
    storageBucket: 'flutter-basics-85cec.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9nF-HMtjQT7l3M2k0Hhfk-8emfNnYFzo',
    appId: '1:507247752159:ios:02a972d19bb7301e100a6a',
    messagingSenderId: '507247752159',
    projectId: 'flutter-basics-85cec',
    storageBucket: 'flutter-basics-85cec.appspot.com',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxmiAg550tVkBW4_zPijLVIG_kA_YH44E',
    appId: '1:507247752159:web:6f2c4432fef67925100a6a',
    messagingSenderId: '507247752159',
    projectId: 'flutter-basics-85cec',
    authDomain: 'flutter-basics-85cec.firebaseapp.com',
    storageBucket: 'flutter-basics-85cec.appspot.com',
    measurementId: 'G-VTMJXN36YN',
  );

}